language: python
python:
- 3.6
cache:
  pip: true
env:
  global:
  - PACKAGE_NAME=wagtail-draftail-snippet
  - PIP_INDEX_URL=$PYPI_URL+simple/
install:
- pip install -U pip
- pip install .
- pip install pytest pytest-django pytest-pythonpath wagtail-factories
script:
- pytest
deploy:
  provider: pypi
  server: $PYPI_URL
  upload_docs: false
  user: travisci
  on:
    tags: true
  password:
    secure: $TRAVIS_CI_PASSWORD
after_deploy:
- curl -X POST "$PIP_INDEX_URL$PACKAGE_NAME/refresh"
